<?php

/**
 * Packfire Dependency Checker (pdc)
 * By Sam-Mauris Yong
 * 
 * Released open source under New BSD 3-Clause License.
 * Copyright (c) Sam-Mauris Yong Shan Xian <sam@mauris.sg>
 * All rights reserved.
 */

namespace Packfire\PDC;

/**
 * Test class for Toolbelt.
 * Generated by PHPUnit on 2012-12-09 at 02:25:32.
 */
class ToolbeltTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Packfire\PDC\Toolbelt::classFromNamespace
     */
    public function testClassFromNamespace() {
        $this->assertEquals('Hurray', Toolbelt::classFromNamespace('\\Bar\\Foo\\Hurray'));
        $this->assertEquals('Hurray', Toolbelt::classFromNamespace('\\Hurray'));
        $this->assertEquals('Hurray', Toolbelt::classFromNamespace('Hurray'));
    }

    /**
     * @covers Packfire\PDC\Toolbelt::significantFigure
     */
    public function testSignificantFigures() {
        $this->assertEquals(1.5, Toolbelt::significantFigure(1.5323, 2));
        $this->assertEquals(1.53, Toolbelt::significantFigure(1.5323));
        $this->assertEquals(153, Toolbelt::significantFigure(153.23));
    }

}