<?php

/**
 * Packfire Dependency Checker (pdc)
 * By Sam-Mauris Yong
 * 
 * Released open source under New BSD 3-Clause License.
 * Copyright (c) Sam-Mauris Yong Shan Xian <sam@mauris.sg>
 * All rights reserved.
 */

namespace Packfire\PDC\Report;

/**
 * Test class for Index.
 * Generated by PHPUnit on 2012-12-09 at 02:34:47.
 */
class IndexTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Index
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Index('%d files', 'No files');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Packfire\PDC\Report\Index::increment
     */
    public function testIncrement() {
        $this->assertCount(0, $this->object);
        $this->object->increment();
        $this->assertCount(1, $this->object);
        $this->object->increment();
        $this->assertCount(2, $this->object);
    }

    /**
     * @covers Packfire\PDC\Report\Index::summary
     */
    public function testSummary() {
        $this->assertEquals('0 files', $this->object->summary());
        $this->object->increment();
        $this->assertEquals('1 files', $this->object->summary());
    }

    /**
     * @covers Packfire\PDC\Report\Index::message
     */
    public function testMessage() {
        $this->assertEquals('No files', $this->object->message());
    }

    /**
     * @covers Packfire\PDC\Report\Index::count
     */
    public function testCount() {
        $this->assertEquals(0, $this->object->count());
        $this->object->increment();
        $this->assertEquals(1, $this->object->count());
    }

}
