<?php
namespace Packfire\PDC\Analyzer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-02 at 22:24:24.
 */
class AnalyzerTest extends \PHPUnit_Framework_TestCase
{
    protected function buildFile($path, $source){
        $file = $this->getMock('\Packfire\PDC\Analyzer\File', array(), array($path));
        $file->expects($this->once())
                ->method('source')
                ->will($this->returnValue($source));
        $file->expects($this->any())
                ->method('path')
                ->will($this->returnValue($path));
        return $file;
    }
    
    protected function buildReport($file){
        $report = $this->getMock('\Packfire\PDC\Report\Report');
        $report->expects($this->once())
                ->method('processFile')
                ->with($file->path());
        return $report;
    }

    /**
     * @covers Packfire\PDC\Analyzer\Analyzer::analyze
     */
    public function testAnalyze()
    {
        $source = <<<'EOT'
<?php
    
class Example{

}
EOT;
        $file = $this->buildFile('Test/Example.php', $source);
        $analyzer = new Analyzer($file);
        $analyzer->analyze($this->buildReport($file));
    }
}
