<?php

/**
 * Packfire Dependency Checker (pdc)
 * By Sam-Mauris Yong
 * 
 * Released open source under New BSD 3-Clause License.
 * Copyright (c) Sam-Mauris Yong Shan Xian <sam@mauris.sg>
 * All rights reserved.
 */

namespace Packfire\PDC\Analyzer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-02 at 12:46:02.
 */
class FileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Packfire\PDC\Analyzer\File::className
     */
    public function testClassName()
    {
        $obj = new File('Test/Complete.php');
        $this->assertEquals('Complete', $obj->className());
    }

    /**
     * @covers Packfire\PDC\Analyzer\File::path
     */
    public function testPath()
    {
        $obj = new File('Test/Complete.php');
        $this->assertEquals('Test/Complete.php', $obj->path());
    }

    /**
     * @covers Packfire\PDC\Analyzer\File::source
     */
    public function testSource()
    {
        $obj = new File(__FILE__);
        $this->assertNotEmpty($obj->source());
    }
}
