<?php

/**
 * Packfire Dependency Checker (pdc)
 * By Sam-Mauris Yong
 * 
 * Released open source under New BSD 3-Clause License.
 * Copyright (c) Sam-Mauris Yong Shan Xian <sam@mauris.sg>
 * All rights reserved.
 */

namespace Packfire\PDC\Analyzer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-02 at 12:46:02.
 */
class FileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Packfire\PDC\Analyzer\File::className
     * @todo   Implement testClassName().
     */
    public function testClassName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Packfire\PDC\Analyzer\File::path
     * @todo   Implement testPath().
     */
    public function testPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Packfire\PDC\Analyzer\File::source
     * @todo   Implement testSource().
     */
    public function testSource()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
